<a href="https://colab.research.google.com/github/sneha31-debug/Global-Air-Pollution/blob/main/Global%20Air%20Pollution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.arange(10)
print(a)
a.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [4]:
a = np.array([[1,2],[3,4]])
print(a)
a.shape

[[1 2]
 [3 4]]


(2, 2)

In [5]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [9]:
a.reshape(4)

array([1, 2, 3, 4])

In [11]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [12]:
a.shape

(2, 2)

In [14]:
a.size

4

In [17]:
a.T

array([[1, 3],
       [2, 4]])

In [18]:
a.dtype

dtype('int64')

In [20]:
a = np.array([[1+3j,1+2j],[1+2j,2+3j]])
b = np.array([[1+3j,1+2j],[1+2j,2+3j]])
a@b

array([[-11.+10.j,  -9.+12.j],
       [ -9.+12.j,  -8.+16.j]])